version: "3.9"
services:
  redis:
    image: redis
    command: redis-server --requirepass 123456789
    ports:
      - "6379:6379"
  web:
    container_name: bankme_test_web
    build:
      context: ./apps/web
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:3000"
    ports:
      - "8080:8080"
  api:
    container_name: bankme_test_api
    restart: on-failure
    depends_on:
      - "redis"
    build:
      context: ./apps/api
    volumes:
      - "data:/data"
    env_file:
      - "./apps/api/.env"
    ports:
      - "3000:3000"
volumes:
  data:
